// swift-tools-version: 5.9

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Vocabulary Game",
    platforms: [
        .iOS("18.0")
    ],
    products: [
        .iOSApplication(
            name: "Vocabulary Game",
            targets: ["AppModule"],
            bundleIdentifier: "mm.vocabularyGame",
            teamIdentifier: "MZD4AGLY32",
            displayVersion: "0.1",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .earth),
            accentColor: .presetColor(.blue),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .microphone(purposeString: "This app requires access to the microphone to enable voice-based interactions. Your voice input is used to recognize and verify spoken vocabulary words."),
                .speechRecognition(purposeString: "This app uses speech recognition to analyze your spoken words and provide feedback on pronunciation.")
            ],
            appCategory: .education
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [
                .process("Resources")
            ],
            swiftSettings: [
                .enableUpcomingFeature("BareSlashRegexLiterals")
            ]
        )
    ]
)
